# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    #vb.customize [ "sharedfolder", "add", :id, "--name", "docker-registry", "--hostpath", File.dirname(__FILE__) + "/repo/docker-registry" ]
    #vb.customize [ "setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/docker-registry", "1" ]
  end

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/xenial64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  #config.vm.network "forwarded_port", guest: 5000, host: 5000

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: "192.168.10.252", nic_type: "virtio"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder "./repo/apt-cacher-ng", "/var/cache/apt-cacher-ng"
  config.vm.synced_folder "./repo/squid", "/var/spool/squid"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  config.vm.provision "shell", inline: <<-SHELL
    timedatectl set-timezone Asia/Shanghai
    #cp -f /vagrant/data/00aptproxy /etc/apt/apt.conf.d/
    #chmod 644 /etc/apt/apt.conf.d/00aptproxy
    umount /var/cache/apt-cacher-ng
    rmdir /var/cache/apt-cacher-ng
    apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:11371 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    add-apt-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
    #add-apt-repository 'deb http://docker.apt.cacher.ng ubuntu-xenial main'
    apt-get update
    apt-get install -y --allow-unauthenticated apt-cacher-ng squid docker-engine
    apt-get upgrade -y
    usermod -aG docker ubuntu
    cp -f /vagrant/data/acng.conf /vagrant/data/backends_docker /etc/apt-cacher-ng/
    cp -f /vagrant/data/squid.conf /etc/squid/
    systemctl disable apt-cacher-ng.service
    systemctl disable squid.service
    docker run -d --name registry --restart on-failure -p 5000:5000 -v /vagrant/config/docker-registry/config.yml:/etc/docker/registry/config.yml -v /vagrant/repo/docker-registry:/var/lib/registry registry
  SHELL

  config.vm.provision "shell", run: "always", inline: <<-SHELL
    mount -t vboxsf -o uid=`id -u apt-cacher-ng`,gid=`id -g apt-cacher-ng` var_cache_apt-cacher-ng /var/cache/apt-cacher-ng
    mount -t vboxsf -o uid=`id -u proxy`,gid=`id -g proxy` var_spool_squid /var/spool/squid
    service apt-cacher-ng start
    service squid start 
    docker start registry
  SHELL

#  config.vm.provision "docker" do |docker|
#    docker.run "registry",
#           auto_assign_name: "registry",
#           args: "-p 5000:5000 -v /vagrant/config/docker-registry/config.yml:/etc/docker/registry/config.yml -v /vagrant/repo/docker-registry:/var/lib/registry",
#           restart: "always"
#  end
end
